// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFavorite(arg1) {
  return window['go']['app']['App']['CreateFavorite'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['app']['App']['CreateProject'](arg1);
}

export function DeleteFavorite(arg1) {
  return window['go']['app']['App']['DeleteFavorite'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function DeleteProjectWithFiles(arg1) {
  return window['go']['app']['App']['DeleteProjectWithFiles'](arg1);
}

export function ExportColorDetailPDF(arg1, arg2) {
  return window['go']['app']['App']['ExportColorDetailPDF'](arg1, arg2);
}

export function ExportComparisonPDF(arg1) {
  return window['go']['app']['App']['ExportComparisonPDF'](arg1);
}

export function ExportPaintByNumbersPDF(arg1) {
  return window['go']['app']['App']['ExportPaintByNumbersPDF'](arg1);
}

export function ExportShoppingListPDF(arg1) {
  return window['go']['app']['App']['ExportShoppingListPDF'](arg1);
}

export function GetFavorite(arg1) {
  return window['go']['app']['App']['GetFavorite'](arg1);
}

export function GetFavorites() {
  return window['go']['app']['App']['GetFavorites']();
}

export function GetImageDataURL(arg1) {
  return window['go']['app']['App']['GetImageDataURL'](arg1);
}

export function GetImagePath(arg1) {
  return window['go']['app']['App']['GetImagePath'](arg1);
}

export function GetImageURL(arg1) {
  return window['go']['app']['App']['GetImageURL'](arg1);
}

export function GetLastRoute() {
  return window['go']['app']['App']['GetLastRoute']();
}

export function GetOwnedPaints() {
  return window['go']['app']['App']['GetOwnedPaints']();
}

export function GetPaint(arg1) {
  return window['go']['app']['App']['GetPaint'](arg1);
}

export function GetPaintFilterOptions() {
  return window['go']['app']['App']['GetPaintFilterOptions']();
}

export function GetPaintProjectCount(arg1) {
  return window['go']['app']['App']['GetPaintProjectCount'](arg1);
}

export function GetPaints() {
  return window['go']['app']['App']['GetPaints']();
}

export function GetProject(arg1) {
  return window['go']['app']['App']['GetProject'](arg1);
}

export function GetProjectColorCount(arg1) {
  return window['go']['app']['App']['GetProjectColorCount'](arg1);
}

export function GetProjectColorsWithMatches(arg1) {
  return window['go']['app']['App']['GetProjectColorsWithMatches'](arg1);
}

export function GetProjectImageAbsPath(arg1) {
  return window['go']['app']['App']['GetProjectImageAbsPath'](arg1);
}

export function GetProjects() {
  return window['go']['app']['App']['GetProjects']();
}

export function GetSidebarWidth() {
  return window['go']['app']['App']['GetSidebarWidth']();
}

export function GetTab(arg1) {
  return window['go']['app']['App']['GetTab'](arg1);
}

export function GetTabRoute(arg1) {
  return window['go']['app']['App']['GetTabRoute'](arg1);
}

export function GetTableState(arg1) {
  return window['go']['app']['App']['GetTableState'](arg1);
}

export function GetThemeState() {
  return window['go']['app']['App']['GetThemeState']();
}

export function ProcessImage(arg1, arg2, arg3) {
  return window['go']['app']['App']['ProcessImage'](arg1, arg2, arg3);
}

export function ReprocessProject(arg1) {
  return window['go']['app']['App']['ReprocessProject'](arg1);
}

export function SaveLastRoute(arg1) {
  return window['go']['app']['App']['SaveLastRoute'](arg1);
}

export function SavePastedImage(arg1) {
  return window['go']['app']['App']['SavePastedImage'](arg1);
}

export function SaveThemeState(arg1) {
  return window['go']['app']['App']['SaveThemeState'](arg1);
}

export function SaveWindowGeometry(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveWindowGeometry'](arg1, arg2, arg3, arg4);
}

export function SelectImageFile() {
  return window['go']['app']['App']['SelectImageFile']();
}

export function SetPaintOwned(arg1, arg2) {
  return window['go']['app']['App']['SetPaintOwned'](arg1, arg2);
}

export function SetSidebarWidth(arg1) {
  return window['go']['app']['App']['SetSidebarWidth'](arg1);
}

export function SetTab(arg1, arg2) {
  return window['go']['app']['App']['SetTab'](arg1, arg2);
}

export function SetTabRoute(arg1, arg2) {
  return window['go']['app']['App']['SetTabRoute'](arg1, arg2);
}

export function SetTableState(arg1, arg2) {
  return window['go']['app']['App']['SetTableState'](arg1, arg2);
}

export function UpdateFavorite(arg1) {
  return window['go']['app']['App']['UpdateFavorite'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['app']['App']['UpdateProject'](arg1);
}
