// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {appkit} from '../models';
import {app} from '../models';

export function CreateFavorite(arg1:db.Favorite):Promise<number>;

export function CreateProject(arg1:db.Project):Promise<number>;

export function DeleteFavorite(arg1:number):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteProjectWithFiles(arg1:number):Promise<void>;

export function ExportColorDetailPDF(arg1:number,arg2:number):Promise<string>;

export function ExportComparisonPDF(arg1:number):Promise<string>;

export function ExportPaintByNumbersPDF(arg1:number):Promise<string>;

export function ExportShoppingListPDF(arg1:number):Promise<string>;

export function GetFavorite(arg1:number):Promise<db.Favorite>;

export function GetFavorites():Promise<Array<db.Favorite>>;

export function GetImageDataURL(arg1:string):Promise<string>;

export function GetImagePath(arg1:string):Promise<string>;

export function GetImageURL(arg1:string):Promise<string>;

export function GetLastRoute():Promise<string>;

export function GetOwnedPaints():Promise<Array<db.Paint>>;

export function GetPaint(arg1:string):Promise<db.Paint>;

export function GetPaintFilterOptions():Promise<db.PaintFilterOptions>;

export function GetPaintProjectCount(arg1:string):Promise<number>;

export function GetPaints():Promise<Array<db.Paint>>;

export function GetProject(arg1:number):Promise<db.Project>;

export function GetProjectColorCount(arg1:number):Promise<number>;

export function GetProjectColorsWithMatches(arg1:number):Promise<Array<db.ProjectColorWithMatches>>;

export function GetProjectImageAbsPath(arg1:number):Promise<string>;

export function GetProjects():Promise<Array<db.Project>>;

export function GetSidebarWidth():Promise<number>;

export function GetTab(arg1:string):Promise<string>;

export function GetTabRoute(arg1:string):Promise<string>;

export function GetTableState(arg1:string):Promise<appkit.TableState>;

export function GetThemeState():Promise<appkit.UIPreferences>;

export function ProcessImage(arg1:string,arg2:string,arg3:number):Promise<app.ProcessingResult>;

export function ReprocessProject(arg1:number):Promise<app.ProcessingResult>;

export function SaveLastRoute(arg1:string):Promise<void>;

export function SavePastedImage(arg1:string):Promise<string>;

export function SaveThemeState(arg1:appkit.UIPreferences):Promise<void>;

export function SaveWindowGeometry(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SelectImageFile():Promise<string>;

export function SetPaintOwned(arg1:string,arg2:boolean):Promise<void>;

export function SetSidebarWidth(arg1:number):Promise<void>;

export function SetTab(arg1:string,arg2:string):Promise<void>;

export function SetTabRoute(arg1:string,arg2:string):Promise<void>;

export function SetTableState(arg1:string,arg2:appkit.TableState):Promise<void>;

export function UpdateFavorite(arg1:db.Favorite):Promise<void>;

export function UpdateProject(arg1:db.Project):Promise<void>;
